project_id = "xridnxtrvtrnqyngrgib"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
# Local development settings
site_url = "http://localhost:8081"
additional_redirect_urls = ["http://localhost:8081"]

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "your-google-client-id"
secret = "your-google-client-secret"
redirect_uri = "http://localhost:54321/auth/v1/callback"

[auth.external.azure]
enabled = true
client_id = "your-azure-client-id"
secret = "your-azure-client-secret"
url = "https://login.microsoftonline.com/common"

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
# ❌ no `realtime.port` — remove it

[studio]
enabled = true
port = 54323

# ❌ Global [functions] table with `enabled/port` is invalid — remove it.
# Define per-function blocks only:

[functions.process-document]
verify_jwt = true

[functions.query-agent]
verify_jwt = true

[edge_runtime]
enabled = true
# ❌ `edge_runtime.port` is invalid; use inspector_port instead if you want it
inspector_port = 54326
