project_id = "xridnxtrvtrnqyngrgib"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

# Disable analytics to remove docker.sock warnings
[analytics]
enabled = false

# Function-level configs
[functions.process-document]
verify_jwt = true

[functions.query-agent]
verify_jwt = true

[edge_runtime]
enabled = true
inspector_port = 54326
