// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xridnxtrvtrnqyngrgib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyaWRueHRydnRybnF5bmdyZ2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODYwOTMsImV4cCI6MjA3MzA2MjA5M30.Tq61SYM5cCIacqBHuvWkaN7Wc8IHmCiTYD1xZpobq6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});